#server config
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
    session:
      cookie:
        http-only: true

spring:
  datasource:
    #local DB config
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/gdl
#    username: root
#    password: password
    
    #local DB config (log4j)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/gdl?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
    
    #CAU DB config
#    url: jdbc:mariadb://192.168.0.23:3306/GDL_LIMS
#    username: GDL_LIMS
#    password: GDLMaria0959!
    
#mybatis config
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true