#server config
server:
  port: 8081

spring:
  datasource:
    #local DB config
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/gdl
    username: root
    password: password
    
#mybatis config
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true