#server config
server:
  port: 8081

spring:
  datasource:
    #local DB config
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/gdl
#    username: root
#    password: password
    url: jdbc:mariadb://192.168.0.23:3306/GDL_LIMS
    username: GDL_LIMS
    password: GDLMaria0959!
    
#mybatis config
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true